#include "palette.hpp"

BlockIdPalette global_palette;

BlockIdPalette::BlockIdPalette() {
	static std::array<const char*, nonsolid_border> nonsolid_blocks{
		"stone_pressure_plate",
		"oak_pressure_plate",
		"spruce_pressure_plate",
		"birch_pressure_plate",
		"dark_oak_pressure_plate",
		"jungle_pressure_plate",
		"acacia_pressure_plate",
		"crimson_pressure_plate",
		"warped_pressure_plate",
		"oak_fence",
		"spruce_fence",
		"birch_fence",
		"dark_oak_fence",
		"jungle_fence",
		"acacia_fence",
		"crimson_fence",
		"warped_fence",
		"stone_slab",
		"oak_slab",
		"spruce_slab",
		"birch_slab",
		"dark_oak_slab",
		"jungle_slab",
		"acacia_slab",
		"crimson_slab",
		"warped_slab",
		"stone_stairs",
		"oak_stairs",
		"spruce_stairs",
		"birch_stairs",
		"dark_oak_stairs",
		"jungle_stairs",
		"acacia_stairs",
		"crimson_stairs",
		"warped_stairs",

		"cobblestone_wall",
		"granite_wall",
		"polished_granite_wall",
		"andesite_wall",
		"polished_andesite_wall",
		"diorite_wall",
		"polished_diorite_wall",
		"sandstone_wall",
		"smooth_sandstone_wall",
		"red_nether_brick_wall",
		"nether_brick_wall",
		"prismarine_wall",
		"prismarine_brick_wall",
		"dark_prismarine_wall",
		"cobblestone_stairs",
		"granite_stairs",
		"polished_granite_stairs",
		"andesite_stairs",
		"polished_andesite_stairs",
		"diorite_stairs",
		"polished_diorite_stairs",
		"sandstone_stairs",
		"smooth_sandstone_stairs",
		"red_nether_brick_stairs",
		"nether_brick_stairs",
		"prismarine_stairs",
		"prismarine_brick_stairs",
		"dark_prismarine_stairs",
		"cobblestone_slab",
		"granite_slab",
		"polished_granite_slab",
		"andesite_slab",
		"polished_andesite_slab",
		"diorite_slab",
		"polished_diorite_slab",
		"sandstone_slab",
		"smooth_sandstone_slab",
		"red_nether_brick_slab",
		"nether_brick_slab",
		"prismarine_slab",
		"prismarine_brick_slab",
		"dark_prismarine_slab",

		"oak_leaves",
		"spruce_leaves",
		"birch_leaves",
		"dark_oak_leaves",
		"jungle_leaves",
		"acacia_leaves",

		"soul_torch",
		"iron_bars",
		"nether_portal",
		"ender_chest",
		"cake",
		"end_portal",
		"end_portal_frame",
		"composter",
		"cauldron",
		"bell",
		"sweet_berry_bush",
		"torch",
		"glass",
		"glass_pane",
		"cactus",
		"ladder",
		"bed",
		"chest",
		"cave_air",
		"water",
		"air"
	};
	// let common block ids clump together
	// (also why nonsolid_blocks has more common stuff last)
	static std::array<const char*, 12> common_blocks{
		"stone",
		"dirt",
		"sand",
		"gravel",
		"diorite",
		"granite",
		"andesite",
		"bedrock",
		"grass_block",
		"sandstone",
		"red_sand",
		"terracotta"
	};
	for (const char* k : nonsolid_blocks) {
		p[k] = next++;
	}
	for (const char* k : common_blocks) {
		p[k] = next++;
	}

	air = p["air"];
	cave_air = p["cave_air"];
}
